LANGUAGE_PHASES = {
    "kotlin": [
        "Structure",
        "Architecture Heatmap",
        "Critical Business Flows",
        "Dependency Explosion Audit",
        "Module Classification",
        "Full Source (AI)",
        "Constitution & Architecture Specs",
        "Cloud Sync & Outbox Engine Audit",
        "Data Flow Tracer",
        "Database Schema",
        "Visual Architecture (Mermaid)",
        "Call Graph",
        "Navigation Graph",
        "DI Graph",
        "UI Map",
        "Risk Analysis",
        "AI Prompt",
        "Executive Summary 2.0"
    ],
    "python": [
        "Structure",
        "Architecture Heatmap",
        "Critical Business Flows",
        "Dependency Explosion Audit",
        "Module Classification",
        "Full Source (AI)",
        "Call Graph",
        "Risk Analysis",
        "AI Prompt",
        "Executive Summary 2.0"
    ],
    "javascript": [
        "Structure",
        "Architecture Heatmap",
        "Critical Business Flows",
        "Dependency Explosion Audit",
        "Module Classification",
        "Full Source (AI)",
        "Firestore & Backend Schema",
        "Web UI & DOM Map",
        "Hardware & Service Integrations",
        "Architecture & Spec Digest",
        "Dependency Graph",
        "Risk Analysis",
        "AI Prompt",
        "Executive Summary 2.0"
    ],
    "java": [
        "Structure",
        "Architecture Heatmap",
        "Critical Business Flows",
        "Dependency Explosion Audit",
        "Module Classification",
        "Full Source (AI)",
        "Call Graph",
        "Risk Analysis",
        "AI Prompt",
        "Executive Summary 2.0"
    ],
    "cpp": [
        "Structure",
        "Architecture Heatmap",
        "Module Classification",
        "Full Source (AI)",
        "Risk Analysis",
        "AI Prompt",
        "Executive Summary 2.0"
    ],
    "all": [
        "Structure",
        "Architecture Heatmap",
        "Module Classification",
        "Full Source (AI)",
        "Risk Analysis",
        "AI Prompt",
        "Executive Summary 2.0"
    ]
}