import os
import re

from core.utils.file_reader import read_text_file
from state.app_state import AppState


def _get_rel_path(p: str) -> str:
    try:
        if AppState.project_root:
            return os.path.relpath(p, AppState.project_root).replace("\\", "/")
        return os.path.basename(p)
    except Exception:
        return os.path.basename(p)


def extract_spec_digest(tree_root):
    """
    Scans project markdown documents, parity specs, and architecture contracts,
    creating a concise, high-value digest for AI auditing.
    """
    doc_files = []

    def walk(node):
        if not node.is_dir and node.name.lower().endswith((".md", ".txt")):
            # Skip output reports and changelogs if generated by this tool
            if not any(sub in node.name.lower() for sub in ["output", "license"]):
                doc_files.append(node.path)

        for c in getattr(node, "children", []):
            walk(c)

    walk(tree_root)

    if not doc_files:
        return (
            "=" * 60 + "\n"
            "ARCHITECTURE & SPEC DIGEST (NO SPEC DOCS DETECTED)\n"
            "=" * 60 + "\n\n"
            "No architecture specifications (.md) found in project directory."
        )

    lines = []
    lines.append("=" * 60)
    lines.append("ARCHITECTURE SPECIFICATIONS & PARITY CONTRACTS DIGEST")
    lines.append("=" * 60)
    lines.append(f"• Total Spec Documents Found: {len(doc_files)}")
    lines.append("")

    for doc_path in sorted(doc_files):
        try:
            content = read_text_file(doc_path, max_size_kb=300)
        except Exception:
            continue

        rel_name = _get_rel_path(doc_path)
        lines.append(f"## 📄 Spec Document: `{rel_name}`")

        # Extract top-level heading
        title_match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
        if title_match:
            lines.append(f"**Title:** {title_match.group(1).strip()}")

        # Extract key H2 headings
        h2_headings = re.findall(r'^##\s+(.+)$', content, re.MULTILINE)
        if h2_headings:
            clean_h2 = [h.strip() for h in h2_headings[:6]]
            lines.append(f"**Key Sections:** {', '.join(clean_h2)}")

        # Extract tables or bullet rules if available
        rule_bullets = re.findall(r'^\s*[-*]\s+(?:\*\*([^*]+)\*\*:\s*)?(.+)$', content, re.MULTILINE)
        if rule_bullets:
            lines.append("**Key Contract Rules / Invariants:**")
            for b_name, b_text in rule_bullets[:5]:
                bullet_str = f"  - {b_name}: {b_text}" if b_name else f"  - {b_text}"
                lines.append(bullet_str[:120])

        lines.append("-" * 40)
        lines.append("")

    lines.append("=" * 60)
    lines.append("INSTRUCTION FOR AI AUDITOR:")
    lines.append("When recommending code changes or refactoring modules, ensure complete compliance")
    lines.append("with the cross-platform parity rules and field canonicalization documented above.")
    lines.append("=" * 60)

    return "\n".join(lines)
